### ISSUE TITLE
make the visuals more basic

### ISSUE THREAD

**Issue by bvreede** [NLeSC/reveal-slides#3]
- no video background
- should not be a reveal tutorial, but a template for nlesc slides, at the very least:
  - title slide
  - slide with an image
  - slide with basic text
  - final slide (with contact info etc)

**Comment by Peter9192** [comment]
Perhaps we can use these mixins for automatically changing text color depending on background

https://github.com/hakimel/reveal.js/blob/4fe3946cb43de57f79aaa7b646aee7e78f4bcc75/css/theme/template/mixins.scss#L31-L45
